name: cartridge
description: isaac mod preset
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 5.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # ── UI / Desktop ────────────────────────────────────────────────────────────
  fluent_ui: ^4.7.7                 # [UI] 데스크톱 Fluent 컴포넌트(예: NavigationView, Pane, InfoBar)
  flutter_reorderable_grid_view: ^5.5.1  # [UI] 그리드 재정렬 위젯(프리셋/모드 카드 재배치)
  window_manager: ^0.5.1            # [Desktop] 창 컨트롤/캡션/드래그 영역 등 윈도우 관리
  url_launcher: ^6.1.12             # [Platform] 외부 링크/앱 열기(워크샵, 문서 등)
  gpt_markdown: ^1.1.4              # [UI] 마크다운 렌더러(도움말/릴리즈노트 등)

  # ── State / Config ──────────────────────────────────────────────────────────
  flutter_riverpod: ^2.3.6          # [State] 전역 상태/DI(예: storeProvider)
  flutter_dotenv: ^6.0.0            # [Config] .env 로드(키/엔드포인트 분리)

  # ── Filesystem / IO ─────────────────────────────────────────────────────────
  path_provider: ^2.0.15            # [FS] 앱/문서 디렉터리 경로 획득(모드 스캔, 프리셋 저장)
  file_selector: ^1.0.3             # [FS/UI] 플랫폼 파일/폴더 선택(네이티브 다이얼로그)
  file: ^7.0.1                      # [FS Abstraction] 테스트 가능한 FileSystem(Local/Memory 교체 DI). 단위테스트에서 MemoryFileSystem 사용
  tailf: ^1.1.0                     # [Logs] 파일 실시간 tail(기록 모드 로그 리딩)
  path: ^1.9.1                      # [FS/Path] 경로 조작(join, basename 등). 런타임에서 저장 경로/파일명 계산에 사용.
  archive: ^4.0.7                   # [Zip] 인스턴스 pack Export/Import용 ZIP 인코딩/디코딩

  # ── Networking / Backend ────────────────────────────────────────────────────
  http: ^1.1.0                      # [Net] REST 호출(업데이트 체크, 서버 연동 등)
  supabase_flutter: ^2.10.0         # [Backend] Supabase 인증/스토리지/DB 연동

  # ── Parsing / Data Utils ────────────────────────────────────────────────────
  xml: ^6.3.0                       # [Parsing] 모드 metadata.xml 파싱
  html: ^0.15.4                     # [Parsing] HTML 파싱/스크래핑(필요 시)
  pub_semver: ^2.1.4                # [Util] 버전 비교/범위 처리(앱/모드 버전 판단)
  uuid: ^4.2.2                      # [Util] 고유 ID 생성(프리셋/엔트리 키 등)
  meta: ^1.16.0                     # [Lang] @immutable/@sealed 등 애노테이션. 컴파일 타임 힌트(런타임 오버헤드 없음)
  json_annotation: ^4.9.0           # [SerDe] JsonSerializable와 함께 쓰는 런타임 애노테이션(@JsonSerializable 등)
  freezed_annotation: ^3.1.0        # [Codegen] Freezed 모델이 import하는 애노테이션(@freezed 등). 런타임 의존.타임 의존.
  collection: ^1.19.1               # [Lang/Util] 확장 컬렉션 유틸(equality, groupBy 등)
  yaml: ^3.1.3                      # [Parsing] 사람 친화 YAML(index.yaml) 파싱(비개발자 친화 목록 관리)

  # ── Features / Misc ─────────────────────────────────────────────────────────
  roulette: ^0.2.0                  # [Feature] 슬롯머신 룰렛(랜덤 회전)
  week_of_year: ^2.2.0              # [Date] 주차 계산(데일리런/통계 등)

  # ── i18n ────────────────────────────────────────────────────────────────────
  flutter_localizations:
    sdk: flutter                    # [i18n] 플러터 기본 현지화 지원
  intl: ^0.20.2                     # [i18n] 날짜·숫자 포맷
  characters: ^1.4.0                # [i18n] 유니코드 문자 경계 처리(다국어 타이틀 파싱 안정성)

  # ── Platform / App Info ─────────────────────────────────────────────────────
  package_info_plus: ^9.0.0         # [Platform] 앱 패키지 버전 조회

  # ── Platform / Windows ──────────────────────────────────────────────────────
  win32_registry: ^2.1.0            # [Windows] 레지스트리 조회(예: Steam 설치 경로 탐색). 런타임 의존.
  sqflite: ^2.4.2                   # [DB] 로컬 SQLite 액세스(설정/캐시/슬롯 데이터 등)
  sqflite_common_ffi: ^2.3.6        # [DB/Desktop] SQLite FFI(Windows/macOS/Linux) — 데스크톱에서 sqflite 대체 백엔드
  super_clipboard: ^0.9.1           # [Clipboard] 선택한 모드 목록을 클립보드로 공유

  # ── Media / Cache ───────────────────────────────────────────────────────────
  crypto: ^3.0.6                    # 이미지 캐싱 할때 해싱으로 사용
  image: ^4.5.4                     # 이미지 캐싱할때 용량 최적화를 위해 이미지 축소하는 기능에 사용하는 패키지


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4                  # [Test] 단위/위젯 테스트용 mocking 프레임워크
  golden_toolkit: ^0.15.0           # [Test/Golden] 골든 이미지 테스트 도구( --update-goldens 로 베이스라인 갱신 )
  flutter_lints: ^6.0.0             # [Lint] 권장 린트 세트(analysis_options.yaml에서 활성화)

  # ── Codegen / Model ─────────────────────────────────────────────────────────
  build_runner: ^2.8.0              # [Codegen] 코드 생성 실행기(Freezed/JsonSerializable 빌드 진입점)
  freezed: ^3.2.2                   # [Codegen] 불변 데이터 클래스/union/sealed 생성기( *.freezed.dart )
  json_serializable: ^6.11.1        # [Codegen] JSON (de)serialize 생성기( *.g.dart )


dependency_overrides:
  # [Compat] fluent_ui의 NumberBox가 사용하는 수식 파서 심볼(ShuntingYardParser)을 제공하기 위해
  # math_expressions를 3.x로 강제 상향합니다.
  # - 증상: 빌드 중 "The method 'ShuntingYardParser' isn't defined" 에러가 발생
  # - 원인: transitive dependency로 낮은 버전(<2.6.0)의 math_expressions가 잠길 때 발생
  # - 배경: fluent_ui >= 4.12.0 경로(예: NumberBox.allowExpressions)에서 해당 심볼 필요
  # - 메모: 상위 패키지들이 의존성 정리 후에는 이 override를 제거할 수 있습니다.
  math_expressions: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/content/
    - assets/images/
    - assets/images/404/
    - assets/images/characters/
    - assets/images/editions/
    - assets/images/promo/
    - assets/images/record_goal/
    - assets/images/screenshots/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example,
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: DSEG7Classic
      fonts:
        - asset: assets/fonts/DSEG7Classic-Regular.ttf
          weight: 400
        - asset: assets/fonts/DSEG7Classic-Bold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DSEG7Classic-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DSEG7Classic-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800

    - family: D2Coding
      fonts:
        - asset: assets/fonts/D2Coding-Ver1.3.2-20180524-ligature.ttf
          weight: 400
        - asset: assets/fonts/D2CodingBold-Ver1.3.2-20180524-ligature.ttf
          weight: 700