on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ github.event_name == 'workflow_dispatch' && 'self-hosted' || 'windows-latest' }}
      steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        - name: Flutter pub get
          run: flutter pub get

        - name: Run build_runner (freezed/json)
          run: flutter pub run build_runner build --delete-conflicting-outputs

        - name: Generate .env file
          run: |
            Set-Content -Path .env -Value 'RECORD_PRESET_URL="${{ secrets.RECORD_PRESET_URL }}"'
            Add-Content -Path .env -Value 'RECORDER_MOD_URL="${{ secrets.RECORDER_MOD_URL }}"'
            Add-Content -Path .env -Value 'SUPABASE_URL="${{ secrets.SUPABASE_URL }}"'
            Add-Content -Path .env -Value 'SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}"'

        - name: Build Windows (Release)
          run: flutter build windows --release

        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: cartridge
            path: ./build/windows/x64/runner/Release

        - name: Compile .ISS to .EXE Installer
          uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
          with:
            path: installer/Cartridge.iss
            options: /O+

        - name: Upload Installer Artifact
          uses: actions/upload-artifact@v4
          with:
            name: installer
            path: installer/Output/*.exe